#pragma once

#define MTASK_VERSION_MAJOR 0
#define MTASK_VERSION_MINOR 1
#define MTASK_VERSION_PATCH 0
#define MTASK_VERSION MTASK_VERSION_MAJOR * 10000 + MTASK_VERSION_MINOR * 100 + MTASK_VERSION_PATCH